# Generated by Django 5.0.4 on 2024-05-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
